---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Install apache2 package
    apt:
      name: apache2
      state: absent

  - name: add php support for apache
    apt:
      name: libeapache2-mod-php
      state: absent
  - name: remove vsftpd
    apt:
      name: vsftpd
      state: absent
