---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["RedHat", "CentOS"]

  - name: Install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstation
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_server
  become: true
  tasks:

  - name: Install apache2 and php package for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - vsftpd
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: Install httpd and php package for CentOS
    tags: apache,httpd,centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_server
  become: true
  tasks:

  - name: Install mariadb package ( Ubuntu )
    tags: mariadb,db,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

# Samba packet is the same for CentOS and Ubuntu, that's why we will use package !!
    # - hosts: file_server
    #package:
    #name: samba
    #state: latest
  
