---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]


    #  - name: Update repository index
    #    dnf:
    #      update_cache: yes
    #    when: ansible_distribution == "CentOS"


